import pandas as pd
import os

input_dir = 'raw_csv'
output_dir = 'replace_csv'

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

csv_files = [f for f in os.listdir(input_dir) if f.endswith('.csv')]

replace_rules = {
    "山(cid:8443)": "山﨑",
    "andShinya": "and Shinya",
    "今泉允聡": "今泉 允聡",
    "栗林健太郎": "栗林 健太郎",
    "大原常徳": "大原 常徳",
    "大聖寺谷一樹": "大聖寺 谷一樹",
    "山内修": "山内 修",
    "齋藤和也": "齋藤 和也",
    "隆藤唯章": "隆藤 唯章",
    "高瀬英希": "高瀬 英希",
    "鈴木貴之": "鈴木 貴之",
    "柴田崇": "柴田 崇",
    "大塚淳": "大塚 淳",
    "中澤栄輔": "中澤 栄輔",
    "小野哲雄": "小野 哲雄",
    "植原亮": "植原 亮",
    "立花幸司": "立花 幸司",
    "上杉繁": "上杉 繁",
    "堀浩一": "堀浩一",
    "関口海良": "関口 海良",
    "内田誠一": "内田 誠一",
    "松原仁": "松原 仁",
    "宿久洋": "宿久 洋",
    "木谷友哉": "木谷 友哉",
    "出分卓矢": "出分 卓矢",
    "HiroakiKitamura": "Hiroaki Kitamura",
    "TomoyaTerada": "Tomoya Terada",
    "ShunsukeNagai": "Shunsuke Nagai",
    "Processing-BasedMotorcycle": "Processing-Based Motorcycle",
    "Systemwith": "System with",
    "anOnboard": "an Onboard",
    "JSAEAnnual": "JSAE Annual",
    "Congress(Autumn)Proceedings": "Congress (Autumn) Proceedings",
    "Yung-ChinChen": "Yung-Chin Chen",
    "SatomiMiyagi": "Satomi Miyagi",
    "KentaroYoshioka": "Kentaro Yoshioka",
    "S.Miyagi": "S. Miyagi",
    "W.Zhang": "W. Zhang",
    "Y.C.Chen": "Y. C. Chen",
    "K.Yoshioka": "K. Yoshioka",
    "KazuyaTomiyama": "Kazuya Tomiyama",
    "YukiYamaguchi": "Yuki Yamaguchi",
    "KazushiMoriishi": "Kazushi Moriishi",
    "D. Fujiki": "D. Fujiki",
    "Akihiro Nishida": "Akihiro Nishida",
    "Thanh V.Pham": "Thanh V. Pham",
    "SusumuIshihara": "Susumu Ishihara",
    "T.Pham": "T. Pham",
    "S.Ishihara": "S. Ishihara",
    "KotaroShimamura": "Kotaro Shimamura",
    "Sun Tanakaand": "Sun Tanaka and",
    "Yuki Hirayama": "Yuki Hirayama",
    "Kengo Suga": "Kengo Suga",
    "MasayoshiTsutsui": "Masayoshi Tsutsui",
    "TatsuyaKaneko": "Tatsuya Kaneko",
    "Takuro Sone": "Takuro Sone",
    "TakehiroMaeda": "Takehiro Maeda",
    "Tomoya Kitani": "Tomoya Kitani",
    "Masayuki Usuiand": "Masayuki Usui and",
    "HaripriyaPasupuleti": "Haripriya Pasupuleti",
    "YoshinaoWada": "Yoshinao Wada",
    "KenjiroYamada": "Kenjiro Yamada",
    "YusukeKanamori": "Yusuke Kanamori",
    "YusukeYamasaki": "Yusuke Yamasaki",
    "ShintaroHosoai": "Shintaro Hosoai",
    "HiroshiNakamura": "Hiroshi Nakamura",
    "HidekiTakase": "Hideki Takase",
    "Y.Chikamoto": "Y. Chikamoto",
    "Y.Tsutsumi": "Y. Tsutsumi",
    "YusukeYamasaki": "Yusuke Yamasaki",
    "Masahiro Kato": "Masahiro Kato",
    "MasaakiImaizumi": "Masaaki Imaizumi",
    "KentaroMinami": "Kentaro Minami",
    "RyotaYasudo": "Ryota Yasudo",
    "KentaroSano": "Kentaro Sano",
    "NobuhoHashimoto": "Nobuho Hashimoto",
    "Sefutsu Ryuand": "Sefutsu Ryu and",
    "Peiqi Zhangand": "Peiqi Zhang and",
    "KeisukeKamahori": "Keisuke Kamahori",
    "M.Kato": "M. Kato",
    "M.Imaizumi": "M. Imaizumi",
    "K.McAlinn": "K. McAlinn",
    "S.Yasui": "S. Yasui",
    "H.Kakehi": "H. Kakehi",
    "ShinyaTakamaeda-Yamazaki": "Shinya Takamaeda-Yamazaki",
    "CentricHybrid": "Centric Hybrid",
    "MemoryArchitecture": "Memory Architecture",
    "ProbabilisticApproximation": "Probabilistic Approximation",
    "IEEE/ACMInternationalConference": "IEEE/ACM International Conference",
    "onComputer-AidedDesign": "on Computer-Aided Design",
    "AnalogComputing-In-Memory": "Analog Computing-In-Memory",
    "Macrowith": "Macro with",
    "SAR-EmbeddedSaliency": "SAR-Embedded Saliency",
    "Dual-treeComplex": "Dual-tree Complex",
    "ofPavement": "of Pavement",
    "ofthe": "of the",
    "40thInternationalSymposium": "40th International Symposium",
    "onAutomation": "on Automation",
    "andRobotics": "and Robotics",
    "inConstruction": "in Construction",
    "forBayesian": "for Bayesian",
    "32ndAnnualInternationalSymposium": "32nd Annual International Symposium",
    "onField-ProgrammableCustomComputingMachines": "on Field-Programmable Custom Computing Machines",
    "On-The-FlySaliency-Aware": "On-The-Fly Saliency-Aware",
    "HybridSRAM": "Hybrid SRAM",
    "29th Asiaand": "29th Asia and",
    "PacificDesignAutomationConference": "Pacific Design Automation Conference",
    "TOPS/WCapacitor-Reconfigured": "TOPS/W Capacitor-Reconfigured",
    "CIMMacro": "CIM Macro",
    "UnifiedAcceleration": "Unified Acceleration",
    "andTransformers": "and Transformers",
    "InternationalSolid-StateCircuitsConference": "International Solid-State Circuits Conference",
    "intermittentpacket": "intermittent packet",
    "transmission methodin": "transmission method in",
    "IEEEInternationalConference": "IEEE International Conference",
    "onPervasiveComputing": "on Pervasive Computing",
    "andCommunicationsWorkshops": "and Communications Workshops",
    "andother": "and other",
    "AffiliatedEvents": "Affiliated Events",
    "videotransmission": "video transmission",
    "forinspection": "for inspection",
    "small diametersewer": "small diameter sewer",
    "multipledrifting": "multiple drifting",
    "InternationalConference": "International Conference",
    "onInformationNetworking": "on Information Networking",
    "BoostingDecision": "Boosting Decision",
    "ConsumerCommunicationsand": "Consumer Communications and",
    "NetworkingConference": "Networking Conference",
    "ArchitectureObfuscation": "Architecture Obfuscation",
    "Sampling-FreeBayesian": "Sampling-Free Bayesian",
    "NetworkAccelerator": "Network Accelerator",
    "GaussianError": "Gaussian Error",
    "SmartphoneApplication": "Smartphone Application",
    "Utility HoleInspection": "Utility Hole Inspection",
    "Mobile Computingand": "Mobile Computing and",
    "UbiquitousNetwork": "Ubiquitous Network",
    "ScramblingFederated": "Scrambling Federated",
    "withDelayed": "with Delayed",
    "Backdoor Attack": "Backdoor Attack",
    "systemfeaturing": "system featuring",
    "EvolvingScholar": "Evolving Scholar",
    "ofMemory": "of Memory",
    "forDecoupled": "for Decoupled",
    "DataOrchestration": "Data Orchestration",
    "InternationalSymposium": "International Symposium",
    "onAppliedReconfigurableComputing": "on Applied Reconfigurable Computing",
    "DataFusion": "Data Fusion",
    "from ConnectedAutonomous": "from Connected Autonomous",
    "toreduce": "to reduce",
    "Network TrafficCongestion": "Network Traffic Congestion",
    "InternationalWorkshop": "International Workshop",
    "onInformatics": "on Informatics",
    "federatedlearning": "federated learning",
    "updatedmodels": "updated models",
    "decentralizedsystems": "decentralized systems",
    "practicalframework": "practical framework",
    "UVs-BasedNarrow": "UVs-Based Narrow",
    "InspectionSystem": "Inspection System",
    "FormationControl": "Formation Control",
    "IntegrityVerification": "Integrity Verification",
    "Symposiumon": "Symposium on",
    "Low-Powerand": "Low-Power and",
    "High-SpeedChips": "High-Speed Chips",
    "andSystems": "and Systems",
    "withMutual": "with Mutual",
    "ConsumerCommunications&": "Consumer Communications &",
    "viaMaximum": "via Maximum",
    "DensityRatio": "Density Ratio",
    "BridgingKL-Divergence": "Bridging KL-Divergence",
    "IntegralProbability": "Integral Probability",
    "ArtificialIntelligence": "Artificial Intelligence",
    "andStatistics": "and Statistics",
    "forBayesian": "for Bayesian",
    "InternationalConference": "International Conference",
    "onField-ProgrammableTechnology": "on Field-Programmable Technology",
    "FederatedReinforcement": "Federated Reinforcement",
    "GlobalCommunicationsConference": "Global Communications Conference",
    "AdaptiveActivation": "Adaptive Activation",
    "BinaryNeural": "Binary Neural",
    "InternationalWorkshop": "International Workshop",
    "onComputerSystems": "on Computer Systems",
    "andArchitectures": "and Architectures",
    "Large-ScaleMeasurement": "Large-Scale Measurement",
    "onLiDAR": "on LiDAR",
    "Attacksagainst": "Attacks against",
    "SIGSACConference": "SIGSAC Conference",
    "onComputer": "on Computer",
    "andCommunicationsSecurity": "and Communications Security",
    "TreeEnsemble": "Tree Ensemble",
    "GuidedBranch": "Guided Branch",
    "InternationalSymposium": "International Symposium",
    "onHighly-EfficientAccelerators": "on Highly-Efficient Accelerators",
    "andReconfigurableTechnologies2022": "and Reconfigurable Technologies 2022",
    "会議 録": "会議録",
    "プロシーデ ィングス": "プロシーディングス",
    "InternationalConference": "International Conference",
    "onLearningRepresentations": "on Learning Representations",
    "StructureLearning": "Structure Learning",
    "DynamicPrecision": "Dynamic Precision",
    "InternationalSymposium": "International Symposium",
    "Solid-StateCircuitsConference": "Solid-State Circuits Conference",
    "pipeinspection": "pipe inspection",
    "InformationNetworking": "Information Networking",
    "IEEEInternational": "IEEE International",
    "IEEEInternational": "IEEE International",
    "FourteenthInternational": "Fourteenth International",
    "UbiquitousNetwork": "Ubiquitous Network",
    "onUbiquitousSecurity": "on Ubiquitous Security",
    "timesynchronization": "time synchronization",
    "TomoyaKitani": "Tomoya Kitani",
    "AppliedReconfigurableComputing": "Applied Reconfigurable Computing",
    "andHideki": "and Hideki",
    "IEEEVehicularNetworking": "IEEE Vehicular Networking",
    "Joint-Subtree": "Joint Subtree",
    "Fog-enabledFederated": "Fog-enabled Federated",
    "ConsumerCommunications": "Consumer Communications",
    "LiDAR-basedObject": "LiDAR-based Object",
    "VehicleSec": "Vehicle Sec",
    "ProbabilityDivergence": "Probability Divergence",
    "DensityRatio": "Density Ratio",
    "ArtificialIntelligence": "Artificial Intelligence",
    "Field-ProgrammableTechnology": "Field-Programmable Technology",
    "FPGA-basedAcceleration": "FPGA-based Acceleration",
    "DepthEstimation": "Depth Estimation",
    "FieldProgrammableTechnology": "Field Programmable Technology",
    "GlobalCommunications": "Global Communications",
    "AdaptiveActivation": "Adaptive Activation",
    "BinaryNeural": "Binary Neural",
    "ComputerSystems": "Computer Systems",
    "andArchitectures": "and Architectures",
    "SIGSACConference": "SIGSAC Conference",
    "CommunicationsSecurity": "Communications Security",
    "TreeEnsemble": "Tree Ensemble",
    "GuidedBranch": "Guided Branch",
    "onHighly-EfficientAccelerators": "on Highly-Efficient Accelerators",
    "andReconfigurableTechnologies": "and Reconfigurable Technologies",
    "onLearningRepresentations": "on Learning Representations",
    "20thConsumer": "20th Consumer",
    "onField-Programmable": "on Field-Programmable",
    "InternationalSymposium": "International Symposium",
    "onEmbeddedMulticore/Many-core": "on Embedded Multicore/Many-core",
    "onMobile": "on Mobile",
    "andUbiquitous": "and Ubiquitous",
    "UbiquitousSecurity": "Ubiquitous Security",
    "andTomoya": "and Tomoya",
    "ofInternational": "of International",
    "2023IEEE": "2023 IEEE",
    "AnnualComputers": "Annual Computers",
    "andApplicationsConference": "and Applications Conference",
    "andT. V.": "and T. V.",
    "IEEEVehicular": "IEEE Vehicular",
    "High-PerformanceJoint": "High-Performance Joint",
    "onField Programmable": "on Field Programmable",
    "2022(GLOBECOM2022)": "2022 (GLOBECOM 2022)",
    "Architectures(CSA 2022)": "Architectures (CSA 2022)",
    "andCommunications": "and Communications",
    "andReconfigurable": "and Reconfigurable",
    "of2024": "of 2024",
    "InternationalSolid-State": "International Solid-State",
    "Conference(ISSCC)": "Conference (ISSCC)",
    "Networking(ICOIN)": "Networking (ICOIN)",
    "onEmbeddedMulticore/Many-core": "on Embedded Multicore/Many-core",
    "2023(UbiSec-2023)": "2023 (UbiSec-2023)",
    "andTomoya": "and Tomoya",
    "andApplicationsConference": "and Applications Conference",
    "Tatsuya Kuboand": "Tatsuya Kubo and",
    "of2023": "of 2023",
    "RemovalAttacks": "Removal Attacks",
    "of2022": "of 2022",
    "ofInternational": "of International",
    "forAutonomous": "for Autonomous",
    "AReview": "A Review",
    "ofHigh-Resolutionand": "of High-Resolution and",
    "Review ofAutomobile": "Review of Automobile",
    "LiDARSoCs:": "LiDAR SoCs:",
    "onElectronics,": "on Electronics,",
    "RobustCurrent": "Robust Current",
    "Switched Capacitor": "Switched Capacitor",
    "ofLaser": "of Laser",
    "onElectronics": "on Electronics",
    "IEICETransactions": "IEICE Transactions",
    "TomoyaWakayama": "Tomoya Wakayama",
    "PerfectClassification": "Perfect Classification",
    "FunctionalData": "Functional Data",
    "forLocal": "for Local",
    "ofStructure": "of Structure",
    "WassersteinDistances": "Wasserstein Distances",
    "MomentPropagation": "Moment Propagation",
    "Analysis ofVariational": "Analysis of Variational",
    "forPractical": "for Practical",
    "DeepLearning": "Deep Learning",
    "IEEETransactions": "IEEE Transactions",
    "onNeural": "on Neural",
    "Networksand": "Networks and",
    "Low-OverheadIntegrity": "Low-Overhead Integrity",
    "onMetadata": "on Metadata",
    "SecureNon-Volatile": "Secure Non-Volatile",
    "MemorySystems": "Memory Systems",
    "forAccurate": "for Accurate",
    "NeuralNetwork": "Neural Network",
    "onInformation": "on Information",
    "RoadUser": "Road User",
    "MaintenancePrioritization": "Maintenance Prioritization",
    "KernelMaximum": "Kernel Maximum",
    "CausalInference": "Causal Inference",
    "Transactionon": "Transaction on",
    "InformationTheory": "Information Theory",
    "InternationalJournal": "International Journal",
    "ofInformaticsSociety": "of Informatics Society",
    "withWasserstein": "with Wasserstein",
    "onGeneral": "on General",
    "EstimatingFunctions": "Estimating Functions",
    "onHypersurface": "on Hypersurface",
    "ofMachine": "of Machine",
    "LearningResearch": "Learning Research",
    "KenjiFukumizu": "Kenji Fukumizu",
    "JohannesSchmidt-Hieber": "Johannes Schmidt-Hieber",
    "Comfortfor": "Comfort for",
    "inBayesian": "in Bayesian",
    "Transactionson": "Transactions on",
    "ReconfigurableTechnology": "Reconfigurable Technology",
    "andSystems": "and Systems",
    "LearningSystems": "Learning Systems",
    "ofDriving": "of Driving",
    "BernardSchölkopf": "Bernard Schölkopf",
    "KrikamolMuandet": "Krikamol Muandet",
    "VariableRegression": "Variable Regression",
    "KernelMaximum": "Kernel Maximum",
    "forDeep": "for Deep",
    "onLoss": "on Loss",
    "SurfaceImplicitRegularization": "Surface Implicit Regularization",
    "BhagawanRokaha": "Bhagawan Rokaha",
    "Bishnu PrasadGautam": "Bishnu Prasad Gautam",
    "withSeamless": "with Seamless",
    "aMultipath": "a Multipath",
    "DetectionApproach": "Detection Approach",
    "andConfidence": "and Confidence",
    "NeuralComputation": "Neural Computation",
    "Construction(ISARC": "Construction (ISARC",
    "ImplicitRegularization": "Implicit Regularization",
    "TomoyaNagatani": "Tomoya Nagatani",
    "High-LevelSynthesis": "High-Level Synthesis",
    "CompilerAutomatically": "Compiler Automatically",
    "SynthesizingMemory": "Synthesizing Memory",
    "IntegrityVerificationEngines": "Integrity Verification Engines",
    "cross-disciplinaryWorkshop": "cross-disciplinary Workshop",
    "onComputingSystems": "on Computing Systems",
    "DaichiTokudaand": "Daichi Tokuda and",
    "forGradient": "for Gradient",
    "BoostingDecision": "Boosting Decision",
    "Bit-LevelEarly-Termination": "Bit-Level Early-Termination",
    "EmbeddedSystems": "Embedded Systems",
    "HardwareCo-designApproach": "Hardware Co-design Approach",
    "Fixed-WeightDNN": "Fixed-Weight DNN",
    "UsingMasked": "Using Masked",
    "AdderTrees": "Adder Trees",
    "AlgorithmwithSparsely": "Algorithm with Sparsely",
    "AssignedScores": "Assigned Scores",
    "forHardware-Efficient": "for Hardware-Efficient",
    "TransferLearning": "Transfer Learning",
    "DeepReinforcement": "Deep Reinforcement",
    "LearningBased": "Learning Based",
    "ResourceAllocationStrategy": "Resource Allocation Strategy",
    "EdgeComputing": "Edge Computing",
    "inUtsunomiya": "in Utsunomiya",
    "曽根卓朗": "曽根 卓朗",
    "中安淳也": "中安 淳也",
    "高前田伸也": "高前田 伸也",
    "武田大輝": "武田 大輝",
    "檜原陽一郎": "檜原 陽一郎",
    "森崇": "森 崇",
    "平鍋健児": "平鍋 健児",
    "高田光隆": "高田 光隆",
    "久保秋真": "久保 秋真",
    "細合晋太郎": "細合 晋太郎",
    "中田雅貴": "中田 雅貴",
    "田中晴亮": "田中 晴亮",
    "中村宏": "中村 宏",
    "AllocationStrategy": "Allocation Strategy",
    "福田竜也": "福田 竜也",
    "宮城竜大": "宮城 竜大",
    "安戸僚汰": "安戸 僚汰",
    "佐野健太郎": "佐野 健太郎",
    "金子竜也": "金子 竜也",
    "藤木大地": "藤木 大地",
    "石原進": "石原 進",
    "丸山健斗": "丸山 健斗",
    "松原克弥": "松原 克弥",
    "山﨑雄輔": "山﨑 雄輔",
    "和田善尚": "和田 善尚",
    "ComputingSystems": "Computing Systems",
    "andProgramming": "and Programming",
    "ComputingIn-Memory": "Computing In-Memory",
    "Saliency-awareFully-Analog": "Saliency-aware Fully-Analog",
    "Edge-PopupAlgorithm": "Edge-Popup Algorithm",
    "西澤渉": "西澤 渉",
    "加藤真大": "加藤 真大",
    "張文倫": "張 文倫",
    "dynamicalsystems": "dynamical systems",
    "andApplications": "and Applications",
    "MachineLearning": "Machine Learning",
    "DynamicalSystems": "Dynamical Systems",
    "FunctionalInference": "Functional Inference",
    "MachineIntelligence": "Machine Intelligence",
    "小宮山純平": "小宮山 純平",
    "柏村周平": "柏村 周平",
    "坂田綾香": "坂田 綾香",
    "吉田直生": "吉田 直生",
    "仲北祥悟": "仲北 祥悟",
    "小野悠太": "小野 悠太",
    "佐藤佑真": "佐藤 佑真",
    "奥野彰文": "奥野 彰文",
    "岡野遼": "岡野 遼",
    "In-ContextLearning": "In-Context Learning",
    "onOverparameterized": "on Overparameterized",
    "onScientific": "on Scientific",
    "andMachine": "and Machine",
    "MitsuhiroOsaki": "Mitsuhiro Osaki",
    "Zenohex:an": "Zenohex: an",
    "StatisticalMathematics": "Statistical Mathematics",
    "RimMeeting": "Rim Meeting",
    "ProcessingSystems": "Processing Systems",
    "Theoriesand": "Theories and",
    "LargeComplex": "Large Complex",
    "ShinKuboaki": "Shin Kuboaki",
    "Hakoniwaand": "Hakoniwa and",
    "deepnetworks": "deep networks",
    "fornonparametric": "for nonparametric",
    "withcorrected": "with corrected",
    "SurfaceImplicit": "Surface Implicit",
    "ofProbability": "of Probability",
    "MathematicalStatistics": "Mathematical Statistics",
    "nonparametricregression": "nonparametric regression",
    "Elixirecosystem": "Elixir ecosystem",
    "Predictionwith": "Prediction with",
    "ofOverparameterized": "of Overparameterized",
    "inOverparameterized": "in Overparameterized",
    "TimeSeries": "Time Series",
    "吉岡健太郎": "吉岡 健太郎",
    "theCloud": "the Cloud",
    "MultiprocessorSoCs": "Multiprocessor SoCs",
    "approximatemessage": "approximate message",
    "LearningSchool": "Learning School",
    "onMachine": "on Machine",
    "Meetingfor": "Meeting for",
    "withAdversarial": "with Adversarial",
    "andMethodological": "and Methodological",
    "andChallenges": "and Challenges",
    "CircuitsConference": "Circuits Conference",
    "電子情報通信学会コンピュータシステム研究会優秀若手発表賞. 村上 太一. ": "村上 太一. 電子情報通信学会コンピュータシステム研究会優秀若手発表賞. ",
}

for file in csv_files:
    data = pd.read_csv(os.path.join(input_dir, file), dtype=str)
    file_base = os.path.splitext(file)[0]

    for old_value, new_value in replace_rules.items():
        data = data.map(lambda x: x.replace(old_value, new_value) if isinstance(x, str) else x)

    data.to_csv(os.path.join(output_dir, f"{file_base}.csv"), index=False, encoding='utf-8-sig')
